/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectProjectIdRouteImport } from './routes/project.$projectId'
import { Route as ApiProvidersRouteImport } from './routes/api/providers'
import { Route as ApiGenerateRouteImport } from './routes/api/generate'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectProjectIdRoute = ProjectProjectIdRouteImport.update({
  id: '/project/$projectId',
  path: '/project/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProvidersRoute = ApiProvidersRouteImport.update({
  id: '/api/providers',
  path: '/api/providers',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateRoute = ApiGenerateRouteImport.update({
  id: '/api/generate',
  path: '/api/generate',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/generate': typeof ApiGenerateRoute
  '/api/providers': typeof ApiProvidersRoute
  '/project/$projectId': typeof ProjectProjectIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/generate': typeof ApiGenerateRoute
  '/api/providers': typeof ApiProvidersRoute
  '/project/$projectId': typeof ProjectProjectIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/generate': typeof ApiGenerateRoute
  '/api/providers': typeof ApiProvidersRoute
  '/project/$projectId': typeof ProjectProjectIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/generate' | '/api/providers' | '/project/$projectId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/generate' | '/api/providers' | '/project/$projectId'
  id:
    | '__root__'
    | '/'
    | '/api/generate'
    | '/api/providers'
    | '/project/$projectId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiGenerateRoute: typeof ApiGenerateRoute
  ApiProvidersRoute: typeof ApiProvidersRoute
  ProjectProjectIdRoute: typeof ProjectProjectIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/$projectId': {
      id: '/project/$projectId'
      path: '/project/$projectId'
      fullPath: '/project/$projectId'
      preLoaderRoute: typeof ProjectProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/providers': {
      id: '/api/providers'
      path: '/api/providers'
      fullPath: '/api/providers'
      preLoaderRoute: typeof ApiProvidersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate': {
      id: '/api/generate'
      path: '/api/generate'
      fullPath: '/api/generate'
      preLoaderRoute: typeof ApiGenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiGenerateRoute: ApiGenerateRoute,
  ApiProvidersRoute: ApiProvidersRoute,
  ProjectProjectIdRoute: ProjectProjectIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
